/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    './app/**/*.{js,ts,jsx,tsx}',
    './pages/**/*.{js,ts,jsx,tsx}',
    './components/**/*.{js,ts,jsx,tsx}',
    './src/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        'inverse-on-surface': '#2e303a',
        'primary-container': '#2e5bff',
        'tertiary-container': '#c24100',
        'on-secondary-fixed-variant': '#004f53',
        'tertiary-fixed': '#ffdbcf',
        'inverse-surface': '#e2e1ef',
        'outline': '#8e90a2',
        'on-surface-variant': '#c4c5d9',
        'tertiary-fixed-dim': '#ffb59b',
        'surface-container-low': '#191b24',
        'on-background': '#e2e1ef',
        'surface': '#11131c',
        'error-container': '#93000a',
        'tertiary': '#ffb59b',
        'outline-variant': '#434656',
        'secondary-fixed-dim': '#00dce6',
        'error': '#ffb4ab',
        'on-tertiary': '#5b1a00',
        'on-secondary': '#00373a',
        'surface-dim': '#11131c',
        'on-primary-fixed': '#001356',
        'primary-fixed': '#dde1ff',
        'surface-container-high': '#282933',
        'surface-bright': '#373943',
        'on-error-container': '#ffdad6',
        'surface-container-lowest': '#0c0e17',
        'surface-variant': '#33343e',
        'on-primary': '#002388',
        'surface-container': '#1d1f29',
        'on-error': '#690005',
        'on-tertiary-fixed': '#380d00',
        'on-secondary-container': '#006a6f',
        'on-primary-fixed-variant': '#0035be',
        'secondary-fixed': '#6ff6ff',
        'on-surface': '#e2e1ef',
        'primary': '#b8c3ff',
        'surface-container-highest': '#33343e',
        'on-tertiary-container': '#ffece6',
        'inverse-primary': '#124af0',
        'on-primary-container': '#efefff',
        'primary-fixed-dim': '#b8c3ff',
        'on-tertiary-fixed-variant': '#812800',
        'secondary': '#dcfdff',
        'on-secondary-fixed': '#002022',
        'background': '#11131c',
        'surface-tint': '#b8c3ff',
        'secondary-container': '#00f1fd',
        // legacy/compat
        'bg-dark': '#0B1220',
        'bg-card': '#111827',
        border: '#1F2937',
        success: '#22C55E',
        warning: '#F59E0B',
      },
      boxShadow: {
        glass: '0 4px 32px 0 rgba(34, 42, 69, 0.12)',
      },
      backgroundImage: {
        'glass': 'linear-gradient(135deg, rgba(255,255,255,0.05) 0%, rgba(66,130,234,0.08) 100%)',
      },
      borderRadius: {
        card: '1.25rem',
      },
      fontFamily: {
        sans: ['Inter', 'ui-sans-serif', 'system-ui'],
        manrope: ['Manrope', 'sans-serif'],
        inter: ['Inter', 'sans-serif'],
        headline: ['Manrope', 'sans-serif'],
        display: ['Manrope', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
      },
    },
  },
  plugins: [],
}
